---
- name: Ansible defaults for GitLab Runner are loaded
  set_fact:
    gitlab_runner: "{{ gitlab_runner_defaults|combine(gitlab_runner) }}"

- name: Ansible variables required to configure GitLab Runner are set
  fail: msg="gitlab_runner.{{ item }} is not defined"
  when: "gitlab_runner[item] is undefined"
  with_items:
    - user
    - home
    - ci_url
    - registration_token
    - known_hosts

- name: GitLab Runner user exists
  user:
    name: "{{ gitlab_runner.user }}"
    home: "{{ gitlab_runner.home }}"
    shell: /usr/local/bin/bash
    generate_ssh_key: true
    ssh_key_file: .ssh/id_rsa
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_comment: "{{ gitlab_runner.user }}@{{ ansible_nodename }}"

- name: GitLab Runner known_hosts are up-to-date
  known_hosts:
    path: "{{ gitlab_runner.home }}/.ssh/known_hosts"
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa {{ item|quote }}') }}"
  with_items: "{{ gitlab_runner.known_hosts }}"

- name: Public key of GitLab Runner user is downloaded
  fetch:
    src: "{{ gitlab_runner.home }}/.ssh/id_rsa.pub"
    dest: "{{ role_path }}/files/public_keys/{{ ansible_nodename }}__{{ gitlab_runner.user }}.pub"
    flat: yes

- debug:
    msg: "Attention: GitLab requires deployment key in '{{ role_path }}/files/public_keys/{{ ansible_nodename }}__{{ gitlab_runner.user }}.pub' for this runner!"

- name: GitLab Runner log file exists
  copy:
    content: ""
    dest: /var/log/gitlab-runner.log
    owner: "{{ gitlab_runner.user }}"
    group: "{{ gitlab_runner.user }}"
    mode: "0640"

- name: GitLab Runner is registered
  command: >
    sudo -i -u {{ gitlab_runner.user|quote }} --
    /usr/local/bin/gitlab-runner register
      --non-interactive
      --description {{ gitlab_runner.user|quote }}@{{ ansible_nodename|quote }}
      --config {{ gitlab_runner.home }}/.gitlab-runner/config.toml
      --url {{ gitlab_runner.ci_url|quote }}
      --registration-token {{ gitlab_runner.registration_token|quote }}
      --executor shell
  args:
    creates: "{{ gitlab_runner.home }}/.gitlab-runner/config.toml"
  notify:
    - Restart GitLab Runner

- name: GitLab Runner service is configured
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^gitlab_runner_dir=
    line: gitlab_runner_dir="{{ gitlab_runner.home }}"
  notify:
    - Restart GitLab Runner

- name: GitLab Runner service is enabled
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^gitlab_runner_enable=
    line: gitlab_runner_enable="YES"

- name: GitLab Runner service is started
  service:
    name: gitlab_runner
    state: started
